MATCH (N) DETACH DELETE N

--CREATE CUSTOMER
CREATE (:CUSTOMER {CUSTOMER_ID: 1, NAME: 'TAHLIL', PHONE_NO: '0181246124', AGE: 18, GENDER: 'MALE', COUNTRY: 'BANGLADESH'});
CREATE (:CUSTOMER {CUSTOMER_ID: 2, NAME: 'MAHFUZ', PHONE_NO: '1461946175', AGE: 19, GENDER: 'MALE', COUNTRY: 'BANGLADESH'});

--CREATE GENRE
CREATE (:GENRE {GENRE_ID: 1, NAME: 'HORROR'})
CREATE (:GENRE {GENRE_ID: 2, NAME: 'THRILLER'})
CREATE (:GENRE {GENRE_ID: 3, NAME: 'ACTION'})

--CREATE AUTHOR
CREATE(:AUTHOR {NAME: 'FARUK', COUNTRY:'INDIA',DATE_OF_BIRTH:date('2001-09-06')})
CREATE(:AUTHOR {NAME: 'NAZMUL', COUNTRY:'BANGLADESH',DATE_OF_BIRTH:date('2211-01-06')})
CREATE(:AUTHOR {NAME: 'TANZIM', COUNTRY:'ENGLAND',DATE_OF_BIRTH:date('1990-09-06')})

--CREATE BOOK
CREATE(:BOOK{TITLE:'BEDER MEYE JOSNA',PUBLISH_YEAR:2001,LANGUAGE:'BANGLA',PAGE_COUNT:1000,PRICE:100});
CREATE(:BOOK{TITLE:'TREASURE ISLAND',PUBLISH_YEAR:2001,LANGUAGE:'ENGLISH',PAGE_COUNT:100,PRICE:2200});
CREATE(:BOOK{TITLE:'SONG OF ICE',PUBLISH_YEAR:2001,LANGUAGE:'ENGLISH',PAGE_COUNT:1230,PRICE:1240});







/* RELATIONSHIPS */

-- CREATE RELATION BETWEEN CUSTOMER AND BOOKS
MATCH (c:CUSTOMER {CUSTOMER_ID: 1}), (b:BOOK {TITLE: 'BEDER MEYE JOSNA'})
CREATE (c)-[:PURCHASED {PURCHASED_DATE: date('2023-04-03'), AMOUNT: 100}]->(b);

-- CREATE CUSTOMER  RATES AUTHOR
MATCH (c:CUSTOMER {CUSTOMER_ID: 1}), (b:AUTHOR {NAME: 'FARUK'})
CREATE (c)-[:RATES{RATING:4.5}]->(b);
MATCH (c:CUSTOMER {CUSTOMER_ID: 2}), (b:AUTHOR {NAME: 'TANZIM'})
CREATE (c)-[:RATES{RATING:3.5}]->(b);

-- CREATE RELATION BOOKS CAN HAVE DIFFERENT VOLUMES
MATCH (b:BOOK {TITLE: 'BEDER MEYE JOSNA'})
SET b.VOLUME = 3

-- CREATE RELATION BOOK GENRE
MATCH (c:BOOK {TITLE:'BEDER MEYE JOSNA'}), (b:GENRE {NAME: 'HORROR'})
CREATE (c)-[:CONSIST_OF]->(b);


-- CREATE AUTHOR WRITES BOOKS INCLUDING WRITING YEAR
MATCH (c:AUTHOR {NAME:'TANZIM'}), (b:BOOK {TITLE:'TREASURE ISLAND'})
CREATE (c)-[:WRITES {WRITING_YEAR: 2018}]->(b);
MATCH (c:AUTHOR {NAME:'FARUK'}), (b:BOOK {TITLE:'BEDER MEYE JOSNA'})
CREATE (c)-[:WRITES {WRITING_YEAR: 2020}]->(b);

-- Add volumes to a particular book
MATCH (b:BOOK {TITLE: 'BEDER MEYE JOSNA'})
SET b.VOLUME = 3





/* QUERIES */
a.
MATCH (c:CUSTOMER)-[p:PURCHASED]->(b:BOOK)
RETURN b.TITLE, SUM(p.AMOUNT) AS TOTAL_REVENUE

b.
MATCH (c:CUSTOMER)-[r:RATES]->(:AUTHOR)-[:WRITES]->(b:BOOK)-[:CONSIST_OF]->(g:GENRE)
RETURN b.TITLE AS BOOK, g.NAME AS GENRE, AVG(r.RATING) AS AVG_RATING


c.
MATCH (c:CUSTOMER {NAME: 'TAHLIL'})-[:PURCHASED {PURCHASED_DATE: date('2023-04-03')}]->(b:BOOK)
RETURN b.TITLE

d.
MATCH (c:CUSTOMER)-[:PURCHASED]->(b:BOOK)
WITH c, COUNT(b) AS book_count
RETURN c.NAME AS Customer, book_count AS `Number of Books Purchased`
ORDER BY book_count DESC LIMIT 1;

e.
MATCH (c:CUSTOMER)-[p:PURCHASED]->(b:BOOK)
RETURN b.TITLE, COUNT(p) AS PURCHASE_COUNT
ORDER BY PURCHASE_COUNT DESC

f.
MATCH (c:CUSTOMER)-[r]-(b:BOOK {TITLE: 'BEDER MEYE JOSNA'})
RETURN c.NAME as Customer_name

g.
MATCH (a:AUTHOR)-[:WRITES]->(b:BOOK)<-[:PURCHASED]-(c:CUSTOMER)
WHERE a.NAME = 'FARUK'
RETURN c.NAME

h.
MATCH (c:CUSTOMER)-[p:PURCHASED]->(b:BOOK {TITLE: 'BEDER MEYE JOSNA'})
WITH c,b.VOLUME AS num_volumes
WHERE num_volumes = 3
RETURN c.NAME AS CUSTOMER_NAME




















